import Head from "next/head";
import Image from "next/image";
import Header from "../src/layouts/Header";
import Banner from "../src/layouts/Banner";
import MobileMenu from "../src/layouts/MobileMenu";
import Footer from "../src/layouts/Footer";
import Hero from "../src/components/AboutPage/Hero";
import About from "../src/components/AboutPage/About";
import Video from "../src/components/AboutPage/Video";
import Team from "../src/components/AboutPage/Team";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Banner /> */}
      <Header />
      {/* <MobileMenu /> */}
      <Hero />
      <About />
      <Video />
      <Team />
      <Footer />
    </div>
  );
}
