import Head from "next/head";
import Image from "next/image";
import Header from "../src/components/LayoutUI/Header";
import Banner from "../src/components/LayoutUI/Banner";
import MobileMenu from "../src/components/LayoutUI/MobileMenu";
import Footer from "../src/components/LayoutUI/Footer";
import SignupForm from "../src/components/Form/SignupForm";

export default function ContactPage() {
  return (
    <div>
      <Head>
        <title>SYCON Clean | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Banner /> */}
      <MobileMenu sticky={true} />
      <Header sticky={true} />
      <div className="contact">
        <div className="container">
          <SignupForm />
        </div>
      </div>
      <Footer />
    </div>
  );
}
