import Head from "next/head";
import Image from "next/image";
import Header from "../src/components/LayoutUI/Header";
import Banner from "../src/components/LayoutUI/Banner";
import MobileMenu from "../src/components/LayoutUI/MobileMenu";
import Footer from "../src/components/LayoutUI/Footer";
import Hero from "../src/components/HomePage/Hero";
import Offer from "../src/components/HomePage/Offer";
import Info from "../src/components/HomePage/Info";
import Info2 from "../src/components/HomePage/Info2";
import Faq from "../src/components/HomePage/FAQ";
import GalleryMenu from "../src/components/HomePage/GalleryMenu";
import Testimonials from "../src/components/HomePage/Testimonials";
import Contact from "../src/components/HomePage/Contact";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <MobileMenu sticky={true} />
      <Header />
      <Hero />
      <Offer />
      <Info />
      <Info2 />
      <Faq />
      <GalleryMenu />
      <Testimonials />
      <Contact />
      <Footer />
    </div>
  );
}
