import Head from "next/head";
import Image from "next/image";
import Header from "../src/components/LayoutUI/Header";
import MobileMenu from "../src/components/LayoutUI/MobileMenu";
import Footer from "../src/components/LayoutUI/Footer";
import Testimonials from "../src/components/HomePage/Testimonials";
import Hero from "../src/components/ServicePage/Hero";
import Services from "../src/components/ServicePage/Services";
export default function Home() {
  return (
    <div>
      <Head>
        <title>SYCON Clean | Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header sticky={true} />
      <MobileMenu sticky={true} />
      <Hero />
      <Services />
      <Testimonials />
      <Footer />
    </div>
  );
}
