import Head from "next/head";
import Image from "next/image";
import Header from "../src/layouts/Header";
import Banner from "../src/layouts/Banner";
import MobileMenu from "../src/layouts/MobileMenu";
import Footer from "../src/layouts/Footer";
import Offer from "../src/components/HomePage/Offer";
import Info from "../src/components/HomePage/Info";
import Info2 from "../src/components/HomePage/Info2";
import GalleryMenu from "../src/components/HomePage/GalleryMenu";
import Testimonials from "../src/components/HomePage/Testimonials";
import Hero from "../src/components/ServicePage/Hero";
import Services from "../src/components/ServicePage/Services";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header sticky={true} />
      {/* <MobileMenu /> */}
      <Hero />
      <Services />
      <Testimonials />
      <Footer />
    </div>
  );
}
